FROM ##from_image##
MAINTAINER mdye <mdye@us.ibm.com>

RUN mkdir -p /usr/local/synchrophasor/
ADD ./pmu-emu /usr/local/synchrophasor/
ADD ./VERSION /usr/local/synchrophasor/

EXPOSE 8008
WORKDIR /usr/local/synchrophasor/
CMD ["./pmu-emu", "-v", "2", "-logtostderr"]
